"""Render manifests/0731-chat-template.jinja against 0731's four golden vectors.

WHY THIS EXISTS: DeepSeek-V4-Flash-0731 ships no Jinja chat template -- the model
card says so and provides encoding_dsv4.py plus four input/output pairs instead.
Crow's operating point runs --jinja, and the whole reasoning-replay chain (1.6 s
against 242.3 s of re-prefill per turn, measured) hangs on the template being
right. So the hand-written template is held against the vectors DeepSeek itself
published, byte for byte.

THE TEMPLATE'S ONE DELIBERATE CHANGE against the donor (the template unsloth
embedded in the preview GGUFs, 13,098 B): on a `task == 'action'` turn the donor
emits an OPENING <think> in thinking mode; golden vector 4 -- generated by
DeepSeek's own reference implementation -- has a CLOSED '</think>' there. An
action turn carries no reasoning. Two occurrences, both corrected.

WHAT GREEN HERE PROVES AND WHAT IT DOES NOT: this renders with Python's jinja2
plus two filters minja also ships (from_json, tojson). llama.cpp renders with
minja. The two engines can disagree, so the operating-point proof is
POST /apply-template against a live server with --chat-template-file -- stage
E10's abort criterion, run when a server is up anyway. A template that fails
HERE is wrong for sure; one that passes is very probably right.

Subcommands, following probe-suite.py's shape:
  check                     all four vectors, one verdict per vector
  check --template <path>   another template, e.g. the donor as negative control
  selftest                  the harness proves it can go red before it says green

Exit 0 = every vector byte-identical.  1 = at least one differs.  2 = setup.
"""

import argparse
import json
import os
import sys

try:
    import jinja2
except ImportError:
    jinja2 = None

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TEMPLATE = os.path.join(REPO, "manifests", "0731-chat-template.jinja")
GOLD = os.path.join(REPO, "manifests", "0731-encoding", "tests")

BOS = "<｜begin▁of▁sentence｜>"
EOS = "<｜end▁of▁sentence｜>"


def load_case(n):
    with open(os.path.join(GOLD, "test_input_%d.json" % n), encoding="utf-8") as fh:
        data = json.load(fh)
    if isinstance(data, dict):
        messages, tools = data["messages"], data.get("tools")
        if tools:
            messages[0]["tools"] = tools
    else:
        messages, tools = data, None
    with open(os.path.join(GOLD, "test_output_%d.txt" % n), encoding="utf-8") as fh:
        gold = fh.read()
    return messages, tools, gold


def render(template_path, messages, tools=None, **extra):
    src = open(template_path, encoding="utf-8").read()
    env = jinja2.Environment(loader=jinja2.BaseLoader(), keep_trailing_newline=True)
    env.policies["json.dumps_kwargs"] = {"ensure_ascii": False}
    # minja ships these; stock jinja2 does not. Without them two vectors do not
    # render at all, which looks like a broken template and is a harness gap.
    env.filters["from_json"] = json.loads
    env.filters["tojson"] = lambda v, **kw: json.dumps(v, ensure_ascii=False, **kw)
    ctx = dict(messages=messages, bos_token=BOS, eos_token=EOS,
               add_generation_prompt=False, thinking=True)
    if tools:
        ctx["tools"] = tools
    ctx.update(extra)
    return env.from_string(src).render(**ctx)


def first_difference(a, b):
    n = min(len(a), len(b))
    i = 0
    while i < n and a[i] == b[i]:
        i += 1
    return i


def check(template_path):
    if not os.path.exists(template_path):
        print("SETUP ERROR: no template at %s" % template_path)
        return 2
    if not os.path.isdir(GOLD):
        print("SETUP ERROR: golden vectors missing at %s" % GOLD)
        return 2

    failed = 0
    for n in (1, 2, 3, 4):
        messages, tools, gold = load_case(n)
        try:
            out = render(template_path, messages, tools)
        except Exception as exc:
            failed += 1
            print("  FAILED   vector %d: render error %s: %s"
                  % (n, type(exc).__name__, str(exc)[:90]))
            continue
        if out == gold:
            print("  OK       vector %d: byte-identical (%d B)" % (n, len(gold)))
        else:
            failed += 1
            i = first_difference(out, gold)
            print("  FAILED   vector %d: first difference at byte %d of %d/%d"
                  % (n, i, len(out), len(gold)))
            print("             rendered: ...%r" % out[max(0, i - 30):i + 30])
            print("             golden  : ...%r" % gold[max(0, i - 30):i + 30])

    # The reasoning_effort half of the criterion: with "max" the output must
    # differ from without, at exactly the marker the template names.
    messages, tools, _ = load_case(2)
    plain = render(template_path, messages, tools)
    maxed = render(template_path, messages, tools, reasoning_effort="max")
    if maxed != plain and "Reasoning Effort: Absolute maximum" in maxed \
            and "Reasoning Effort: Absolute maximum" not in plain:
        print("  OK       reasoning_effort=max changes the render at its own marker")
    else:
        failed += 1
        print("  FAILED   reasoning_effort=max: differs=%s, marker in maxed=%s, in plain=%s"
              % (maxed != plain, "Reasoning Effort: Absolute maximum" in maxed,
                 "Reasoning Effort: Absolute maximum" in plain))

    print()
    print("RESULT: %s" % ("4 of 4 vectors byte-identical, effort marker behaves"
                          if not failed else "%d check(s) FAILED" % failed))
    return 1 if failed else 0


def selftest():
    """The harness can go red. A comparator that cannot is a decoration."""
    import tempfile
    failed = 0

    def case(label, cond):
        nonlocal failed
        if cond:
            print("  ok   %s" % label)
        else:
            failed = 1
            print("  FAIL %s" % label)

    # 1 - the real template passes (positive control for the cases below).
    case("the shipped template passes", check_quiet(TEMPLATE) == 0)

    # 2 - one character changed -> red. E10's own counter-probe, automated: a
    #     space after the assistant tag shifts every vector.
    src = open(TEMPLATE, encoding="utf-8").read()
    broken = src.replace("<｜Assistant｜>", "<｜Assistant｜> ", 1)
    with tempfile.NamedTemporaryFile("w", suffix=".jinja", delete=False,
                                     encoding="utf-8", newline="") as fh:
        fh.write(broken)
        p = fh.name
    try:
        case("one added space turns vectors red", check_quiet(p) == 1)
    finally:
        os.unlink(p)

    # 3 - the donor as negative control. It must fail vector 4 (the action
    #     turn), or this suite cannot tell the fixed template from its donor.
    donor = os.path.join(REPO, "manifests", "gguf-meta-0.0.6",
                         "chat_template-DeepSeek-V4-Flash-UD-IQ3_XXS-00001-of-00004.jinja")
    case("the donor template fails (vector 4)", check_quiet(donor) == 1)

    # 4 - a missing template is a setup error, not a pass.
    case("a missing template is a setup error", check_quiet(os.path.join(REPO, "nope.jinja")) == 2)

    print()
    print("RESULT: %s" % ("HARNESS OK - it can go red and knows the donor from the fix"
                          if not failed else "HARNESS BROKEN"))
    return failed


def check_quiet(path):
    import contextlib
    import io as _io
    buf = _io.StringIO()
    with contextlib.redirect_stdout(buf):
        return check(path)


def main(argv):
    if jinja2 is None:
        print("SETUP ERROR: jinja2 not available in this Python")
        return 2
    ap = argparse.ArgumentParser()
    sub = ap.add_subparsers(dest="cmd", required=True)
    p_check = sub.add_parser("check")
    p_check.add_argument("--template", default=TEMPLATE)
    sub.add_parser("selftest")
    args = ap.parse_args(argv[1:])
    if args.cmd == "selftest":
        return selftest()
    return check(args.template)


if __name__ == "__main__":
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    sys.exit(main(sys.argv))
